name: Docker Build and Push

on:
  push:
    branches:
      - main
     


jobs:
  approved:
    runs-on: self-hosted
    steps:

     - name: Set up QEMU
       uses: docker/setup-qemu-action@v3
      
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
      
     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
     - name: Build and push
       uses: docker/build-push-action@v6
       with:
           push: true
           tags: smtmdeepak/myapp:latest


    

 #   steps:
  #    - name: Checkout code
   #     uses: actions/checkout@v4

      #- name: Run Trivy vulnerability scanner in repo mode
      #  uses: aquasecurity/trivy-action@0.20.0
       # with:
        #  scan-type: 'fs'
         # ignore-unfixed: true
          #format: 'sarif'
          #output: 'trivy-results.sarif'
          #severity: 'LOW'

      #- name: Upload Trivy scan results to GitHub Security tab
     #   uses: github/codeql-action/upload-sarif@v3
      #  with:
       #   sarif_file: 'trivy-results.sarif'

    #  - name: Set up Docker Buildx
     #   uses: docker/setup-buildx-action@v3

     # - name: Log in to Docker Hub
     #   uses: docker/login-action@v3
     #   with:
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}

     # - name: Build and push Docker image
     #   uses: docker/build-push-action@v5
     #   with:
      #    context: .
       #   push: true
        #  tags: smtmdeepak/myapp:${{ github.sha }}


    #  - name: Log in to Docker Hub
     #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

     # - name: Build and push Docker image
      #  run: |
       #   docker build -t smtmdeepak/myapp:latest .
        #  docker push smtmdeepak/myapp:latest
          
      
  #    - name: Notify success
   #     if: success()
    #    run: echo "Docker image built and pushed successfully!"
