name: Docker Build and Push

on:
 # push:
 pull_request:
    types: [closed]
    branches:
      - main
     


jobs:
  approved:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
  
    steps:
     - name: Checkout code
       uses: actions/checkout@v4
       
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
       
     -  name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

     - name: Build and push Docker image
       run: |
          docker build -t smtmdeepak/myapp:${{github.sha}} .
          docker push smtmdeepak/myapp:${{github.sha}}
          
      
  #    - name: Notify success
   #     if: success()
#    #    run: echo "Docker image built and pushed successfully!"
